export const SET_AUTHENTICATED = "SET_AUTHENTICATED";
export const IS_AUTHENTICATED = "IS_AUTHENTICATED";

export const SET_TOKEN = "SET_TOKEN";
export const IS_TOKEN_SET = "IS_TOKEN_SET";

export const SET_BALLOT_ADDRESS = "SET_BALLOT_ADDRESS";
export const SET_CONTRACT = "SET_CONTRACT";
export const SET_ACCOUNT = "SET_ACCOUNT";
export const SET_CONNECTION_URL = "SET_CONNECTION_URL";

export const SET_CASTED_VOTE = "SET_CASTED_VOTE";

export const CHANGE_SYSTEM_LANGUAGE = "CHANGE_SYSTEM_LANGUAGE";
