export const SmsApiErrors = {
  400: {
    BAD_REQUEST: 'BAD_REQUEST',
    INVALID_PHONE_NR: 'INVALID_PHONE_NR',
    RESOURCE_NOT_FOUND: 'RESOURCE_NOT_FOUND',
  },

  401: {
    AUTH_FAILED: 'AUTH_FAILED',
  },

  404: {
    INVALID_VERIFICAION_CODE: 'INVALID_VERIFICAION_CODE',
  },

  500: {
    VERIFICAION_IS_NOT_WORKING: 'VERIFICAION_IS_NOT_WORKING',
  },
};
