export const UserApiErrors = {
  409: {
    NATIONAL_ID_EXISTS: 'NATIONAL_ID_EXISTS',
    PASSPORT_NR_EXISTS: 'PASSPORT_NR_EXISTS',
    PHONE_NR_EXISTS: 'PHONE_NR_EXISTS',
  },
  400: {
    INVALID_PHONE_NR: 'INVALID_PHONE_NR',
    INVALID_VERIFICATION_CODE: 'INVALID_VERIFICATION_CODE',
    INVALID_PASSPORT_NR: 'INVALID_PASSPORT_NR',
    INVALID_NATIONAL_IDENTITY: 'INVALID_NATIONAL_IDENTITY',
  },
  406: {
    ANSWERS_NOT_FOUND: 'ANSWERS_NOT_FOUND',
    IMAGES_NOT_FOUND: 'IMAGES_NOT_FOUND',
  },

  412: {
    PRECONDITION_FAILED: 'PRECONDITION_FAILED',
  },

  404: {
    USER_NOT_FOUND: 'USER_NOT_FOUND',
  },
};
