version: "3"
services:
  member_portal0:
    container_name: guardian_frontend0
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    ports:
      - 3000:3000
  member_portal1:
    container_name: guardian_frontend1
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    ports:
      - 3001:3000
  member_portal2:
    container_name: guardian_frontend2
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    ports:
      - 3002:3000
  member_portal3:
    container_name: guardian_frontend3
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      REACT_APP_PORT: 9002

    env_file:
      - .env
    ports:
      - 3003:3000
